version: "3.9"
services:
  nats:
    image: nats
    entrypoint: /nats-server
    command: "-js -m 5555"
    ports:
      - 4222:4222
      - 5555:5555
    networks: [ "test_network" ]
  postgresnode:
    image: postgres:15
    container_name: postgresnode
    restart: always
    environment:
      POSTGRES_PASSWORD: mindsoftware
      POSTGRES_USER: mindsoftware
      POSTGRES_DB: mindsoftware
    volumes:
      - ./volumes/db1:/var/lib/postgresql/data
    networks: [ "test_network" ]
  postgresnode2:
    image: postgres:15
    container_name: postgresnode2
    restart: always
    environment:
      POSTGRES_PASSWORD: mindsoftware
      POSTGRES_USER: mindsoftware
      POSTGRES_DB: mindsoftware
    volumes:
      - ./volumes/db2:/var/lib/postgresql/data
    networks: [ "test_network" ]

  worker:
    build: ./mind-software
    restart: always
    ports:
      - 2112:2112
    depends_on:
      - postgresnode
      - postgresnode2
      - nats
    environment:
      REDIS_IP: "redis-master"
      REDIS_PASSWORD: "mindsoftware_pass"

      POSTGRES_IPS: "postgresnode,postgresnode2"
      POSTGRES_PORT: "5432"
      POSTGRES_PASSWORD: mindsoftware
      POSTGRES_USER: mindsoftware
      POSTGRES_DB: mindsoftware

      NATS_URL: nats://nats:4222
      MODE: debug
    networks: [ "test_network" ]
    deploy:
      mode: replicated
      replicas: 1

  publisher:
    build: ./publisher
    restart: always
    depends_on:
      - postgresnode
      - postgresnode2
      - nats
    environment:
      NATS_URL: nats://nats:4222
      QUERIES_MIN: 10
    networks: [ "test_network" ]


networks:
  test_network:
    driver: bridge