name: Go package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19.5'

      - name: Build
        run: go build -v ./...
        working-directory: ./mind-software

      - name: Test
        run: go test -v ./mind-software/...
        working-directory: ./mind-software
